name: Release

on:
  push:
    tags:
      - "*"

jobs:
  linux:
    name: Linux x86_64 GNU
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Compress release
        run: tar czvf release-test.tar.gz -C target/release release-test

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release-test.tar.gz
          asset_name: release-test-Linux-x86_64.tar.gz
          tag: ${{ github.ref }}
    
    linux_musl:
      name: Linux x86_64 Glibc
      runs-on: ubuntu-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v3

        - name: Install toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            target: x86_64-unknown-linux-musl
            override: true

        - name: Build
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release

        - name: Compress release
          run: tar czvf release-test.tar.gz -C target/x86_64-unknown-linux-musl/release release-test

        - name: Upload release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: release-test.tar.gz
            asset_name: release-test-Linux-musl-x86_64.tar.gz
            tag: ${{ github.ref }}
    

    macos:
      name: macOS x86_64
      runs-on: macos-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v3

        - name: Install toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            override: true

        - name: Build
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release

        - name: Compress release
          run: tar czvf release-test.tar.gz -C target/release release-test

        - name: Upload release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: release-test.tar.gz
            asset_name: release-test-macOS-x86_64.tar.gz
            tag: ${{ github.ref }}
    

    macos_arm:
      name: macOS arm64
      runs-on: macos-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v3

        - name: Install toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            target: aarch64-apple-darwin
            override: true

        - name: Build
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release --target aarch64-apple-darwin

        - name: Compress release
          run: tar czvf release-test.tar.gz -C target/aarch64-apple-darwin/release release-test

        - name: Upload release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: release-test.tar.gz
            asset_name: release-test-macOS-arm64.tar.gz
            tag: ${{ github.ref }}
    
    windows:
      name: Windows x86_64
      runs-on: windows-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v3

        - name: Install toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            override: true

        - name: Build
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release

        - name: Compress release
          run: tar czvf release-test.tar.gz -C target/release release-test

        - name: Upload release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: release-test.tar.gz
            asset_name: release-test-Windows-x86_64.tar.gz
            tag: ${{ github.ref }}